// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salesforce/cdp/queryservice/v1/query_service.proto

package com.salesforce.a360.queryservice.grpc.v1;

public interface AnsiSqlQueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salesforce.cdp.queryservice.v1.AnsiSqlQueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 1;</code>
   * @return The query.
   */
  String getQuery();
  /**
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();

  /**
   * <code>int32 limit = 2;</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <code>int32 offset = 3;</code>
   * @return The offset.
   */
  int getOffset();

  /**
   * <code>repeated string orderbys = 4;</code>
   * @return A list containing the orderbys.
   */
  java.util.List<String>
      getOrderbysList();
  /**
   * <code>repeated string orderbys = 4;</code>
   * @return The count of orderbys.
   */
  int getOrderbysCount();
  /**
   * <code>repeated string orderbys = 4;</code>
   * @param index The index of the element to return.
   * @return The orderbys at the given index.
   */
  String getOrderbys(int index);
  /**
   * <code>repeated string orderbys = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the orderbys at the given index.
   */
  com.google.protobuf.ByteString
      getOrderbysBytes(int index);

  /**
   * <code>string tenant_id = 5;</code>
   * @return The tenantId.
   */
  String getTenantId();
  /**
   * <code>string tenant_id = 5;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string dataspace_name = 6;</code>
   * @return The dataspaceName.
   */
  String getDataspaceName();
  /**
   * <code>string dataspace_name = 6;</code>
   * @return The bytes for dataspaceName.
   */
  com.google.protobuf.ByteString
      getDataspaceNameBytes();
}
