// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salesforce/cdp/queryservice/v1/query_service.proto

package com.salesforce.a360.queryservice.grpc.v1;

public interface AnsiSqlExtractQueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salesforce.cdp.queryservice.v1.AnsiSqlExtractQueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 1;</code>
   * @return The query.
   */
  java.lang.String getQuery();
  /**
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();

  /**
   * <code>repeated .google.protobuf.Any params = 2;</code>
   */
  java.util.List<com.google.protobuf.Any> 
      getParamsList();
  /**
   * <code>repeated .google.protobuf.Any params = 2;</code>
   */
  com.google.protobuf.Any getParams(int index);
  /**
   * <code>repeated .google.protobuf.Any params = 2;</code>
   */
  int getParamsCount();
  /**
   * <code>repeated .google.protobuf.Any params = 2;</code>
   */
  java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getParamsOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Any params = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getParamsOrBuilder(
      int index);

  /**
   * <code>string data_space = 4;</code>
   * @return The dataSpace.
   */
  java.lang.String getDataSpace();
  /**
   * <code>string data_space = 4;</code>
   * @return The bytes for dataSpace.
   */
  com.google.protobuf.ByteString
      getDataSpaceBytes();
}
