// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salesforce/cdp/queryservice/v1/query_service.proto

package com.salesforce.a360.queryservice.grpc.v1;

public interface AnsiSqlQueryStreamResponseChunkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponseChunk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .google.protobuf.ListValue data = 1;</code>
   */
  java.util.List<com.google.protobuf.ListValue> 
      getDataList();
  /**
   * <code>repeated .google.protobuf.ListValue data = 1;</code>
   */
  com.google.protobuf.ListValue getData(int index);
  /**
   * <code>repeated .google.protobuf.ListValue data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .google.protobuf.ListValue data = 1;</code>
   */
  java.util.List<? extends com.google.protobuf.ListValueOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .google.protobuf.ListValue data = 1;</code>
   */
  com.google.protobuf.ListValueOrBuilder getDataOrBuilder(
      int index);
}
