// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salesforce/cdp/queryservice/v1/query_service.proto

package com.salesforce.a360.queryservice.grpc.v1;

public interface AnsiSqlQueryStreamArrowResponseChunkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamArrowResponseChunk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 127;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
