// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salesforce/cdp/queryservice/v1/query_service.proto

package com.salesforce.a360.queryservice.grpc.v1;

/**
 * Protobuf type {@code salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponse}
 */
public final class AnsiSqlQueryStreamResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponse)
    AnsiSqlQueryStreamResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AnsiSqlQueryStreamResponse.newBuilder() to construct.
  private AnsiSqlQueryStreamResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnsiSqlQueryStreamResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AnsiSqlQueryStreamResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AnsiSqlQueryStreamResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata.Builder subBuilder = null;
            if (resultCase_ == 1) {
              subBuilder = ((com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata) result_).toBuilder();
            }
            result_ =
                input.readMessage(com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata) result_);
              result_ = subBuilder.buildPartial();
            }
            resultCase_ = 1;
            break;
          }
          case 18: {
            com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk.Builder subBuilder = null;
            if (resultCase_ == 2) {
              subBuilder = ((com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk) result_).toBuilder();
            }
            result_ =
                input.readMessage(com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk) result_);
              result_ = subBuilder.buildPartial();
            }
            resultCase_ = 2;
            break;
          }
          case 26: {
            com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk.Builder subBuilder = null;
            if (resultCase_ == 3) {
              subBuilder = ((com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk) result_).toBuilder();
            }
            result_ =
                input.readMessage(com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk) result_);
              result_ = subBuilder.buildPartial();
            }
            resultCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.salesforce.a360.queryservice.grpc.v1.QueryServiceProto.internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.salesforce.a360.queryservice.grpc.v1.QueryServiceProto.internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse.class, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse.Builder.class);
  }

  private int resultCase_ = 0;
  private java.lang.Object result_;
  public enum ResultCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    METADATA(1),
    RESPONSE_CHUNK(2),
    ARROW_RESPONSE_CHUNK(3),
    RESULT_NOT_SET(0);
    private final int value;
    private ResultCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCase forNumber(int value) {
      switch (value) {
        case 1: return METADATA;
        case 2: return RESPONSE_CHUNK;
        case 3: return ARROW_RESPONSE_CHUNK;
        case 0: return RESULT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResultCase
  getResultCase() {
    return ResultCase.forNumber(
        resultCase_);
  }

  public static final int METADATA_FIELD_NUMBER = 1;
  /**
   * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamMetadata metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return resultCase_ == 1;
  }
  /**
   * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamMetadata metadata = 1;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata getMetadata() {
    if (resultCase_ == 1) {
       return (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata) result_;
    }
    return com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata.getDefaultInstance();
  }
  /**
   * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamMetadata metadata = 1;</code>
   */
  @java.lang.Override
  public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadataOrBuilder getMetadataOrBuilder() {
    if (resultCase_ == 1) {
       return (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata) result_;
    }
    return com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata.getDefaultInstance();
  }

  public static final int RESPONSE_CHUNK_FIELD_NUMBER = 2;
  /**
   * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponseChunk response_chunk = 2;</code>
   * @return Whether the responseChunk field is set.
   */
  @java.lang.Override
  public boolean hasResponseChunk() {
    return resultCase_ == 2;
  }
  /**
   * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponseChunk response_chunk = 2;</code>
   * @return The responseChunk.
   */
  @java.lang.Override
  public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk getResponseChunk() {
    if (resultCase_ == 2) {
       return (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk) result_;
    }
    return com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk.getDefaultInstance();
  }
  /**
   * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponseChunk response_chunk = 2;</code>
   */
  @java.lang.Override
  public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunkOrBuilder getResponseChunkOrBuilder() {
    if (resultCase_ == 2) {
       return (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk) result_;
    }
    return com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk.getDefaultInstance();
  }

  public static final int ARROW_RESPONSE_CHUNK_FIELD_NUMBER = 3;
  /**
   * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamArrowResponseChunk arrow_response_chunk = 3;</code>
   * @return Whether the arrowResponseChunk field is set.
   */
  @java.lang.Override
  public boolean hasArrowResponseChunk() {
    return resultCase_ == 3;
  }
  /**
   * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamArrowResponseChunk arrow_response_chunk = 3;</code>
   * @return The arrowResponseChunk.
   */
  @java.lang.Override
  public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk getArrowResponseChunk() {
    if (resultCase_ == 3) {
       return (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk) result_;
    }
    return com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk.getDefaultInstance();
  }
  /**
   * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamArrowResponseChunk arrow_response_chunk = 3;</code>
   */
  @java.lang.Override
  public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunkOrBuilder getArrowResponseChunkOrBuilder() {
    if (resultCase_ == 3) {
       return (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk) result_;
    }
    return com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resultCase_ == 1) {
      output.writeMessage(1, (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata) result_);
    }
    if (resultCase_ == 2) {
      output.writeMessage(2, (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk) result_);
    }
    if (resultCase_ == 3) {
      output.writeMessage(3, (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk) result_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resultCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata) result_);
    }
    if (resultCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk) result_);
    }
    if (resultCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk) result_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse)) {
      return super.equals(obj);
    }
    com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse other = (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse) obj;

    if (!getResultCase().equals(other.getResultCase())) return false;
    switch (resultCase_) {
      case 1:
        if (!getMetadata()
            .equals(other.getMetadata())) return false;
        break;
      case 2:
        if (!getResponseChunk()
            .equals(other.getResponseChunk())) return false;
        break;
      case 3:
        if (!getArrowResponseChunk()
            .equals(other.getArrowResponseChunk())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (resultCase_) {
      case 1:
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + getMetadata().hashCode();
        break;
      case 2:
        hash = (37 * hash) + RESPONSE_CHUNK_FIELD_NUMBER;
        hash = (53 * hash) + getResponseChunk().hashCode();
        break;
      case 3:
        hash = (37 * hash) + ARROW_RESPONSE_CHUNK_FIELD_NUMBER;
        hash = (53 * hash) + getArrowResponseChunk().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponse)
      com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.salesforce.a360.queryservice.grpc.v1.QueryServiceProto.internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.salesforce.a360.queryservice.grpc.v1.QueryServiceProto.internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse.class, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse.Builder.class);
    }

    // Construct using com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      resultCase_ = 0;
      result_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.salesforce.a360.queryservice.grpc.v1.QueryServiceProto.internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponse_descriptor;
    }

    @java.lang.Override
    public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse getDefaultInstanceForType() {
      return com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse build() {
      com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse buildPartial() {
      com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse result = new com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse(this);
      if (resultCase_ == 1) {
        if (metadataBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = metadataBuilder_.build();
        }
      }
      if (resultCase_ == 2) {
        if (responseChunkBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = responseChunkBuilder_.build();
        }
      }
      if (resultCase_ == 3) {
        if (arrowResponseChunkBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = arrowResponseChunkBuilder_.build();
        }
      }
      result.resultCase_ = resultCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse) {
        return mergeFrom((com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse other) {
      if (other == com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse.getDefaultInstance()) return this;
      switch (other.getResultCase()) {
        case METADATA: {
          mergeMetadata(other.getMetadata());
          break;
        }
        case RESPONSE_CHUNK: {
          mergeResponseChunk(other.getResponseChunk());
          break;
        }
        case ARROW_RESPONSE_CHUNK: {
          mergeArrowResponseChunk(other.getArrowResponseChunk());
          break;
        }
        case RESULT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int resultCase_ = 0;
    private java.lang.Object result_;
    public ResultCase
        getResultCase() {
      return ResultCase.forNumber(
          resultCase_);
    }

    public Builder clearResult() {
      resultCase_ = 0;
      result_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata.Builder, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadataOrBuilder> metadataBuilder_;
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamMetadata metadata = 1;</code>
     * @return Whether the metadata field is set.
     */
    @java.lang.Override
    public boolean hasMetadata() {
      return resultCase_ == 1;
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamMetadata metadata = 1;</code>
     * @return The metadata.
     */
    @java.lang.Override
    public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata getMetadata() {
      if (metadataBuilder_ == null) {
        if (resultCase_ == 1) {
          return (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata) result_;
        }
        return com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata.getDefaultInstance();
      } else {
        if (resultCase_ == 1) {
          return metadataBuilder_.getMessage();
        }
        return com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata.getDefaultInstance();
      }
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamMetadata metadata = 1;</code>
     */
    public Builder setMetadata(com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        metadataBuilder_.setMessage(value);
      }
      resultCase_ = 1;
      return this;
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamMetadata metadata = 1;</code>
     */
    public Builder setMetadata(
        com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 1;
      return this;
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamMetadata metadata = 1;</code>
     */
    public Builder mergeMetadata(com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata value) {
      if (metadataBuilder_ == null) {
        if (resultCase_ == 1 &&
            result_ != com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata.getDefaultInstance()) {
          result_ = com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata.newBuilder((com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 1) {
          metadataBuilder_.mergeFrom(value);
        }
        metadataBuilder_.setMessage(value);
      }
      resultCase_ = 1;
      return this;
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamMetadata metadata = 1;</code>
     */
    public Builder clearMetadata() {
      if (metadataBuilder_ == null) {
        if (resultCase_ == 1) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 1) {
          resultCase_ = 0;
          result_ = null;
        }
        metadataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamMetadata metadata = 1;</code>
     */
    public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata.Builder getMetadataBuilder() {
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamMetadata metadata = 1;</code>
     */
    @java.lang.Override
    public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadataOrBuilder getMetadataOrBuilder() {
      if ((resultCase_ == 1) && (metadataBuilder_ != null)) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 1) {
          return (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata) result_;
        }
        return com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata.getDefaultInstance();
      }
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamMetadata metadata = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata.Builder, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadataOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        if (!(resultCase_ == 1)) {
          result_ = com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata.getDefaultInstance();
        }
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata.Builder, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadataOrBuilder>(
                (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamMetadata) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 1;
      onChanged();;
      return metadataBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk.Builder, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunkOrBuilder> responseChunkBuilder_;
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponseChunk response_chunk = 2;</code>
     * @return Whether the responseChunk field is set.
     */
    @java.lang.Override
    public boolean hasResponseChunk() {
      return resultCase_ == 2;
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponseChunk response_chunk = 2;</code>
     * @return The responseChunk.
     */
    @java.lang.Override
    public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk getResponseChunk() {
      if (responseChunkBuilder_ == null) {
        if (resultCase_ == 2) {
          return (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk) result_;
        }
        return com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk.getDefaultInstance();
      } else {
        if (resultCase_ == 2) {
          return responseChunkBuilder_.getMessage();
        }
        return com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk.getDefaultInstance();
      }
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponseChunk response_chunk = 2;</code>
     */
    public Builder setResponseChunk(com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk value) {
      if (responseChunkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        responseChunkBuilder_.setMessage(value);
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponseChunk response_chunk = 2;</code>
     */
    public Builder setResponseChunk(
        com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk.Builder builderForValue) {
      if (responseChunkBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        responseChunkBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponseChunk response_chunk = 2;</code>
     */
    public Builder mergeResponseChunk(com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk value) {
      if (responseChunkBuilder_ == null) {
        if (resultCase_ == 2 &&
            result_ != com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk.getDefaultInstance()) {
          result_ = com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk.newBuilder((com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 2) {
          responseChunkBuilder_.mergeFrom(value);
        }
        responseChunkBuilder_.setMessage(value);
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponseChunk response_chunk = 2;</code>
     */
    public Builder clearResponseChunk() {
      if (responseChunkBuilder_ == null) {
        if (resultCase_ == 2) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 2) {
          resultCase_ = 0;
          result_ = null;
        }
        responseChunkBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponseChunk response_chunk = 2;</code>
     */
    public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk.Builder getResponseChunkBuilder() {
      return getResponseChunkFieldBuilder().getBuilder();
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponseChunk response_chunk = 2;</code>
     */
    @java.lang.Override
    public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunkOrBuilder getResponseChunkOrBuilder() {
      if ((resultCase_ == 2) && (responseChunkBuilder_ != null)) {
        return responseChunkBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 2) {
          return (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk) result_;
        }
        return com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk.getDefaultInstance();
      }
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponseChunk response_chunk = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk.Builder, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunkOrBuilder> 
        getResponseChunkFieldBuilder() {
      if (responseChunkBuilder_ == null) {
        if (!(resultCase_ == 2)) {
          result_ = com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk.getDefaultInstance();
        }
        responseChunkBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk.Builder, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunkOrBuilder>(
                (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponseChunk) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 2;
      onChanged();;
      return responseChunkBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk.Builder, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunkOrBuilder> arrowResponseChunkBuilder_;
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamArrowResponseChunk arrow_response_chunk = 3;</code>
     * @return Whether the arrowResponseChunk field is set.
     */
    @java.lang.Override
    public boolean hasArrowResponseChunk() {
      return resultCase_ == 3;
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamArrowResponseChunk arrow_response_chunk = 3;</code>
     * @return The arrowResponseChunk.
     */
    @java.lang.Override
    public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk getArrowResponseChunk() {
      if (arrowResponseChunkBuilder_ == null) {
        if (resultCase_ == 3) {
          return (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk) result_;
        }
        return com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk.getDefaultInstance();
      } else {
        if (resultCase_ == 3) {
          return arrowResponseChunkBuilder_.getMessage();
        }
        return com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk.getDefaultInstance();
      }
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamArrowResponseChunk arrow_response_chunk = 3;</code>
     */
    public Builder setArrowResponseChunk(com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk value) {
      if (arrowResponseChunkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        arrowResponseChunkBuilder_.setMessage(value);
      }
      resultCase_ = 3;
      return this;
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamArrowResponseChunk arrow_response_chunk = 3;</code>
     */
    public Builder setArrowResponseChunk(
        com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk.Builder builderForValue) {
      if (arrowResponseChunkBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        arrowResponseChunkBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 3;
      return this;
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamArrowResponseChunk arrow_response_chunk = 3;</code>
     */
    public Builder mergeArrowResponseChunk(com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk value) {
      if (arrowResponseChunkBuilder_ == null) {
        if (resultCase_ == 3 &&
            result_ != com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk.getDefaultInstance()) {
          result_ = com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk.newBuilder((com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 3) {
          arrowResponseChunkBuilder_.mergeFrom(value);
        }
        arrowResponseChunkBuilder_.setMessage(value);
      }
      resultCase_ = 3;
      return this;
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamArrowResponseChunk arrow_response_chunk = 3;</code>
     */
    public Builder clearArrowResponseChunk() {
      if (arrowResponseChunkBuilder_ == null) {
        if (resultCase_ == 3) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 3) {
          resultCase_ = 0;
          result_ = null;
        }
        arrowResponseChunkBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamArrowResponseChunk arrow_response_chunk = 3;</code>
     */
    public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk.Builder getArrowResponseChunkBuilder() {
      return getArrowResponseChunkFieldBuilder().getBuilder();
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamArrowResponseChunk arrow_response_chunk = 3;</code>
     */
    @java.lang.Override
    public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunkOrBuilder getArrowResponseChunkOrBuilder() {
      if ((resultCase_ == 3) && (arrowResponseChunkBuilder_ != null)) {
        return arrowResponseChunkBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 3) {
          return (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk) result_;
        }
        return com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk.getDefaultInstance();
      }
    }
    /**
     * <code>.salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamArrowResponseChunk arrow_response_chunk = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk.Builder, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunkOrBuilder> 
        getArrowResponseChunkFieldBuilder() {
      if (arrowResponseChunkBuilder_ == null) {
        if (!(resultCase_ == 3)) {
          result_ = com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk.getDefaultInstance();
        }
        arrowResponseChunkBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk.Builder, com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunkOrBuilder>(
                (com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamArrowResponseChunk) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 3;
      onChanged();;
      return arrowResponseChunkBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponse)
  }

  // @@protoc_insertion_point(class_scope:salesforce.cdp.queryservice.v1.AnsiSqlQueryStreamResponse)
  private static final com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse();
  }

  public static com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnsiSqlQueryStreamResponse>
      PARSER = new com.google.protobuf.AbstractParser<AnsiSqlQueryStreamResponse>() {
    @java.lang.Override
    public AnsiSqlQueryStreamResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AnsiSqlQueryStreamResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AnsiSqlQueryStreamResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnsiSqlQueryStreamResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.salesforce.a360.queryservice.grpc.v1.AnsiSqlQueryStreamResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

