// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salesforce/cdp/queryservice/v1/query_service.proto

package com.salesforce.a360.queryservice.grpc.v1;

public interface AnsiSqlQueryResponseV2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:salesforce.cdp.queryservice.v1.AnsiSqlQueryResponseV2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 row_count = 1;</code>
   * @return The rowCount.
   */
  int getRowCount();

  /**
   * <code>bool done = 2;</code>
   * @return The done.
   */
  boolean getDone();

  /**
   * <code>string query_id = 3;</code>
   * @return The queryId.
   */
  java.lang.String getQueryId();
  /**
   * <code>string query_id = 3;</code>
   * @return The bytes for queryId.
   */
  com.google.protobuf.ByteString
      getQueryIdBytes();

  /**
   * <code>string start_time = 4;</code>
   * @return The startTime.
   */
  java.lang.String getStartTime();
  /**
   * <code>string start_time = 4;</code>
   * @return The bytes for startTime.
   */
  com.google.protobuf.ByteString
      getStartTimeBytes();

  /**
   * <code>string end_time = 5;</code>
   * @return The endTime.
   */
  java.lang.String getEndTime();
  /**
   * <code>string end_time = 5;</code>
   * @return The bytes for endTime.
   */
  com.google.protobuf.ByteString
      getEndTimeBytes();

  /**
   * <code>.google.protobuf.Struct metadata = 6;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.google.protobuf.Struct metadata = 6;</code>
   * @return The metadata.
   */
  com.google.protobuf.Struct getMetadata();
  /**
   * <code>.google.protobuf.Struct metadata = 6;</code>
   */
  com.google.protobuf.StructOrBuilder getMetadataOrBuilder();

  /**
   * <code>repeated string data = 7;</code>
   * @return A list containing the data.
   */
  java.util.List<java.lang.String>
      getDataList();
  /**
   * <code>repeated string data = 7;</code>
   * @return The count of data.
   */
  int getDataCount();
  /**
   * <code>repeated string data = 7;</code>
   * @param index The index of the element to return.
   * @return The data at the given index.
   */
  java.lang.String getData(int index);
  /**
   * <code>repeated string data = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the data at the given index.
   */
  com.google.protobuf.ByteString
      getDataBytes(int index);
}
