// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salesforce/cdp/queryservice/v1/query_service.proto

package com.salesforce.a360.queryservice.grpc.v1;

/**
 * Protobuf enum {@code salesforce.cdp.queryservice.v1.OutputFormat}
 */
public enum OutputFormat
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNSPECIFIED = 0;</code>
   */
  UNSPECIFIED(0),
  /**
   * <code>TEXT = 1;</code>
   */
  TEXT(1),
  /**
   * <code>ARROW = 2;</code>
   */
  ARROW(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNSPECIFIED = 0;</code>
   */
  public static final int UNSPECIFIED_VALUE = 0;
  /**
   * <code>TEXT = 1;</code>
   */
  public static final int TEXT_VALUE = 1;
  /**
   * <code>ARROW = 2;</code>
   */
  public static final int ARROW_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OutputFormat valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OutputFormat forNumber(int value) {
    switch (value) {
      case 0: return UNSPECIFIED;
      case 1: return TEXT;
      case 2: return ARROW;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OutputFormat>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OutputFormat> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OutputFormat>() {
          public OutputFormat findValueByNumber(int number) {
            return OutputFormat.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.salesforce.a360.queryservice.grpc.v1.QueryServiceProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final OutputFormat[] VALUES = values();

  public static OutputFormat valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OutputFormat(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:salesforce.cdp.queryservice.v1.OutputFormat)
}

