// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salesforce/cdp/queryservice/v1/query_service.proto

package com.salesforce.a360.queryservice.grpc.v1;

public final class QueryServiceProto {
  private QueryServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponseV2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponseV2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponseChunk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponseChunk_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n2salesforce/cdp/queryservice/v1/query_s" +
      "ervice.proto\022\036salesforce.cdp.queryservic" +
      "e.v1\032\031google/protobuf/any.proto\032\034google/" +
      "protobuf/struct.proto\"x\n\032AnsiSqlExtractQ" +
      "ueryRequest\022\r\n\005query\030\001 \001(\t\022$\n\006params\030\002 \003" +
      "(\0132\024.google.protobuf.Any\022\021\n\ttenant_id\030\003 " +
      "\001(\t\022\022\n\ndata_space\030\004 \001(\t\"=\n\033AnsiSqlExtrac" +
      "tQueryResponse\022\020\n\010query_id\030\001 \001(\t\022\014\n\004data" +
      "\030\002 \001(\014\"\200\001\n\023AnsiSqlQueryRequest\022\r\n\005query\030" +
      "\001 \001(\t\022\r\n\005limit\030\002 \001(\005\022\016\n\006offset\030\003 \001(\005\022\020\n\010" +
      "orderbys\030\004 \003(\t\022\021\n\ttenant_id\030\005 \001(\t\022\026\n\016dat" +
      "aspace_name\030\006 \001(\t\"\301\001\n\024AnsiSqlQueryRespon" +
      "se\022\021\n\trow_count\030\001 \001(\005\022\014\n\004done\030\002 \001(\010\022\020\n\010q" +
      "uery_id\030\003 \001(\t\022\022\n\nstart_time\030\004 \001(\t\022\020\n\010end" +
      "_time\030\005 \001(\t\022)\n\010metadata\030\006 \001(\0132\027.google.p" +
      "rotobuf.Struct\022%\n\004data\030\007 \003(\0132\027.google.pr" +
      "otobuf.Struct\"\252\001\n\026AnsiSqlQueryResponseV2" +
      "\022\021\n\trow_count\030\001 \001(\005\022\014\n\004done\030\002 \001(\010\022\020\n\010que" +
      "ry_id\030\003 \001(\t\022\022\n\nstart_time\030\004 \001(\t\022\020\n\010end_t" +
      "ime\030\005 \001(\t\022)\n\010metadata\030\006 \001(\0132\027.google.pro" +
      "tobuf.Struct\022\014\n\004data\030\007 \003(\t\"*\n\031AnsiSqlQue" +
      "ryStreamRequest\022\r\n\005query\030\001 \001(\t\"\321\001\n\032AnsiS" +
      "qlQueryStreamResponse\022N\n\010metadata\030\001 \001(\0132" +
      ":.salesforce.cdp.queryservice.v1.AnsiSql" +
      "QueryStreamMetadataH\000\022Y\n\016response_chunk\030" +
      "\002 \001(\0132?.salesforce.cdp.queryservice.v1.A" +
      "nsiSqlQueryStreamResponseChunkH\000B\010\n\006resu" +
      "lt\"G\n\032AnsiSqlQueryStreamMetadata\022)\n\010meta" +
      "data\030\001 \001(\0132\027.google.protobuf.Struct\"K\n\037A" +
      "nsiSqlQueryStreamResponseChunk\022(\n\004rows\030\001" +
      " \003(\0132\032.google.protobuf.ListValue2\274\004\n\014Que" +
      "ryService\022{\n\014AnsiSqlQuery\0223.salesforce.c" +
      "dp.queryservice.v1.AnsiSqlQueryRequest\0324" +
      ".salesforce.cdp.queryservice.v1.AnsiSqlQ" +
      "ueryResponse\"\000\022\210\001\n\025AnsiSqlQueryStreaming" +
      "\0223.salesforce.cdp.queryservice.v1.AnsiSq" +
      "lQueryRequest\0326.salesforce.cdp.queryserv" +
      "ice.v1.AnsiSqlQueryResponseV2\"\0000\001\022\217\001\n\022An" +
      "siSqlQueryStream\0229.salesforce.cdp.querys" +
      "ervice.v1.AnsiSqlQueryStreamRequest\032:.sa" +
      "lesforce.cdp.queryservice.v1.AnsiSqlQuer" +
      "yStreamResponse\"\0000\001\022\221\001\n\022AniSqlExtractQue" +
      "ry\022:.salesforce.cdp.queryservice.v1.Ansi" +
      "SqlExtractQueryRequest\032;.salesforce.cdp." +
      "queryservice.v1.AnsiSqlExtractQueryRespo" +
      "nse\"\0000\001B?\n(com.salesforce.a360.queryserv" +
      "ice.grpc.v1B\021QueryServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryRequest_descriptor,
        new String[] { "Query", "Params", "TenantId", "DataSpace", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryResponse_descriptor,
        new String[] { "QueryId", "Data", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryRequest_descriptor,
        new String[] { "Query", "Limit", "Offset", "Orderbys", "TenantId", "DataspaceName", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponse_descriptor,
        new String[] { "RowCount", "Done", "QueryId", "StartTime", "EndTime", "Metadata", "Data", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponseV2_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponseV2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponseV2_descriptor,
        new String[] { "RowCount", "Done", "QueryId", "StartTime", "EndTime", "Metadata", "Data", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamRequest_descriptor,
        new String[] { "Query", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponse_descriptor,
        new String[] { "Metadata", "ResponseChunk", "Result", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamMetadata_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamMetadata_descriptor,
        new String[] { "Metadata", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponseChunk_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponseChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponseChunk_descriptor,
        new String[] { "Rows", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
