// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salesforce/cdp/queryservice/v1/query_service.proto

package com.salesforce.a360.queryservice.grpc.v1;

public final class QueryServiceProto {
  private QueryServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponseV2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponseV2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponseChunk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponseChunk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamArrowResponseChunk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamArrowResponseChunk_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2salesforce/cdp/queryservice/v1/query_s" +
      "ervice.proto\022\036salesforce.cdp.queryservic" +
      "e.v1\032\031google/protobuf/any.proto\032\034google/" +
      "protobuf/struct.proto\"e\n\032AnsiSqlExtractQ" +
      "ueryRequest\022\r\n\005query\030\001 \001(\t\022$\n\006params\030\002 \003" +
      "(\0132\024.google.protobuf.Any\022\022\n\ndata_space\030\004" +
      " \001(\t\"=\n\033AnsiSqlExtractQueryResponse\022\020\n\010q" +
      "uery_id\030\001 \001(\t\022\014\n\004data\030\002 \001(\014\"\200\001\n\023AnsiSqlQ" +
      "ueryRequest\022\r\n\005query\030\001 \001(\t\022\r\n\005limit\030\002 \001(" +
      "\005\022\016\n\006offset\030\003 \001(\005\022\020\n\010orderbys\030\004 \003(\t\022\021\n\tt" +
      "enant_id\030\005 \001(\t\022\026\n\016dataspace_name\030\006 \001(\t\"\301" +
      "\001\n\024AnsiSqlQueryResponse\022\021\n\trow_count\030\001 \001" +
      "(\005\022\014\n\004done\030\002 \001(\010\022\020\n\010query_id\030\003 \001(\t\022\022\n\nst" +
      "art_time\030\004 \001(\t\022\020\n\010end_time\030\005 \001(\t\022)\n\010meta" +
      "data\030\006 \001(\0132\027.google.protobuf.Struct\022%\n\004d" +
      "ata\030\007 \003(\0132\027.google.protobuf.Struct\"\252\001\n\026A" +
      "nsiSqlQueryResponseV2\022\021\n\trow_count\030\001 \001(\005" +
      "\022\014\n\004done\030\002 \001(\010\022\020\n\010query_id\030\003 \001(\t\022\022\n\nstar" +
      "t_time\030\004 \001(\t\022\020\n\010end_time\030\005 \001(\t\022)\n\010metada" +
      "ta\030\006 \001(\0132\027.google.protobuf.Struct\022\014\n\004dat" +
      "a\030\007 \003(\t\"o\n\031AnsiSqlQueryStreamRequest\022\r\n\005" +
      "query\030\001 \001(\t\022C\n\routput_format\030\002 \001(\0162,.sal" +
      "esforce.cdp.queryservice.v1.OutputFormat" +
      "\"\267\002\n\032AnsiSqlQueryStreamResponse\022N\n\010metad" +
      "ata\030\001 \001(\0132:.salesforce.cdp.queryservice." +
      "v1.AnsiSqlQueryStreamMetadataH\000\022Y\n\016respo" +
      "nse_chunk\030\002 \001(\0132?.salesforce.cdp.queryse" +
      "rvice.v1.AnsiSqlQueryStreamResponseChunk" +
      "H\000\022d\n\024arrow_response_chunk\030\003 \001(\0132D.sales" +
      "force.cdp.queryservice.v1.AnsiSqlQuerySt" +
      "reamArrowResponseChunkH\000B\010\n\006result\"G\n\032An" +
      "siSqlQueryStreamMetadata\022)\n\010metadata\030\001 \001" +
      "(\0132\027.google.protobuf.Struct\"K\n\037AnsiSqlQu" +
      "eryStreamResponseChunk\022(\n\004rows\030\001 \003(\0132\032.g" +
      "oogle.protobuf.ListValue\"4\n$AnsiSqlQuery" +
      "StreamArrowResponseChunk\022\014\n\004data\030\177 \001(\014*4" +
      "\n\014OutputFormat\022\017\n\013UNSPECIFIED\020\000\022\010\n\004TEXT\020" +
      "\001\022\t\n\005ARROW\020\0022\275\004\n\014QueryService\022{\n\014AnsiSql" +
      "Query\0223.salesforce.cdp.queryservice.v1.A" +
      "nsiSqlQueryRequest\0324.salesforce.cdp.quer" +
      "yservice.v1.AnsiSqlQueryResponse\"\000\022\210\001\n\025A" +
      "nsiSqlQueryStreaming\0223.salesforce.cdp.qu" +
      "eryservice.v1.AnsiSqlQueryRequest\0326.sale" +
      "sforce.cdp.queryservice.v1.AnsiSqlQueryR" +
      "esponseV2\"\0000\001\022\217\001\n\022AnsiSqlQueryStream\0229.s" +
      "alesforce.cdp.queryservice.v1.AnsiSqlQue" +
      "ryStreamRequest\032:.salesforce.cdp.queryse" +
      "rvice.v1.AnsiSqlQueryStreamResponse\"\0000\001\022" +
      "\222\001\n\023AnsiSqlExtractQuery\022:.salesforce.cdp" +
      ".queryservice.v1.AnsiSqlExtractQueryRequ" +
      "est\032;.salesforce.cdp.queryservice.v1.Ans" +
      "iSqlExtractQueryResponse\"\0000\001B?\n(com.sale" +
      "sforce.a360.queryservice.grpc.v1B\021QueryS" +
      "erviceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryRequest_descriptor,
        new java.lang.String[] { "Query", "Params", "DataSpace", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlExtractQueryResponse_descriptor,
        new java.lang.String[] { "QueryId", "Data", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryRequest_descriptor,
        new java.lang.String[] { "Query", "Limit", "Offset", "Orderbys", "TenantId", "DataspaceName", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponse_descriptor,
        new java.lang.String[] { "RowCount", "Done", "QueryId", "StartTime", "EndTime", "Metadata", "Data", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponseV2_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponseV2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryResponseV2_descriptor,
        new java.lang.String[] { "RowCount", "Done", "QueryId", "StartTime", "EndTime", "Metadata", "Data", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamRequest_descriptor,
        new java.lang.String[] { "Query", "OutputFormat", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponse_descriptor,
        new java.lang.String[] { "Metadata", "ResponseChunk", "ArrowResponseChunk", "Result", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamMetadata_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamMetadata_descriptor,
        new java.lang.String[] { "Metadata", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponseChunk_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponseChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamResponseChunk_descriptor,
        new java.lang.String[] { "Rows", });
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamArrowResponseChunk_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamArrowResponseChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesforce_cdp_queryservice_v1_AnsiSqlQueryStreamArrowResponseChunk_descriptor,
        new java.lang.String[] { "Data", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
